inf = input("Escolha uma palavra: ")
print(inf.isalnum())
print(inf.isalpha())
print(inf.isdigit())
print(inf.islower())
print(inf.isupper())
print(inf.isspace())
print(inf.istitle())
print(inf.isprintable())
print(inf.isidentifier())
print(inf.isnumeric())
print(inf.isdecimal())
print(inf.isascii())
